# -*- coding: utf-8 -*-
"""Stage_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1csTu8IxaQ1MzzoNEUD_6vjRy_7g0prmI
"""

import json
import math

file = open("/home/subho/Downloads/stage_2.json", "r")
data = json.load(file)

detail_stats = {}
rev_summ_stats = {}

def calculate_trendiness(rating_div, oldest_rev, newest_rev):
    # Assuming maximum customer count for this apparel as 10000
    max_cnt = 10000
    if len(rating_div) == 0:
        return None
    
    # Assuming weightage scale [-2, -1, 0, 0.5, 1]
    score = rating_div['5'] * 1 + rating_div['4']*0.5 + rating_div['3']*0
    score += rating_div['2'] * (-1) + rating_div['1']*-2
    
    #normalizing score
    score /= rating_div["1"] + rating_div["2"] + rating_div["3"] + rating_div["4"] + rating_div["5"]
    score *= max_cnt
     
    if oldest_rev is None:
        # Since, generally the newest product have few ratings
        time_diff = 5
    else :
        # time_diff is the number of days since introduction of the product
        time_diff = (newest_rev - oldest_rev)/86400
    
    # More rating in less time means more trendy
    score /= time_diff
    
    return score

def calculate_score

modified_json = []
for item in data:
    # Copy everything except oldest_rev, newest_rev, 
    # rating_div
    item_new = {}

    item_new["id"] = item["id"]
    item_new["title"] = item["title"]
    item_new["rating_div"] = item["rating_div"]
    item_new["image"] = item["image"]
    item_new["rev_summ"] = item["rev_summ"]
    item_new["detail"] = item["detail"]
    
    rating_div = item["rating_div"]
    oldest_rev = item["oldest_rev"]
    newest_rev = item["newest_rev"]
     
    score = calculate_trendiness(rating_div, oldest_rev, newest_rev)
    if score is None :
        continue
    item_new["score"] = score
    modified_json.append(item_new)

modified_json

for item in dat